### PR TITLE
Upgrade bdv and imglib dependencies while keeping scijava and spark version.

### PR DESCRIPTION
**Pull request by kgabor**
* New version of bigdataviewer-vistools, imglib2-cache for wrapAsVolatile and CachedCellImage signature updates.
 * Added imbglib2, n5-imglib2, n5-zarr versions so that pom-scijava can be left unchanged.
 * For unknown reasons, pulled in spark dependencies changed and scala-lang 2.11.12 must be added explicitly, otherwise omitted.
 * Update fusion method signatures in AffineFusion changed after multiview-reconstruction 1.0.1 -> downsampling removed for fusion methods.
 * Added released bigdataviewer-omezarr as zarr dependency.
 * Fix duplicate classes.
 * Fix n5 compression annotation jsons.
 * pom reformatting
 * Excluding ijp-kheops bioformats from multiview-reconstruction. Source of most conflict. BS-S does not need it.

### CODE REVIEW

**Comment by kgabor** [comment]
In a 1-machine setup, the fatjar works for me with `spark-submit`, with the ancient `gson` version problem inherited from `spark-2.4.7`. Needs @trautmane 's workaround. (https://github.com/PreibischLab/BigStitcher-Spark/issues/11)

**Comment by StephanPreibisch** [comment]
@trautmane - could you please check this out?

**Comment by StephanPreibisch** [comment]
Excluding ijp-kheops bioformats from multiview-reconstruction makes total sense, only required for OpenSeaDragon export ...

**Comment by StephanPreibisch** [comment]
Note: I'll also make a new branch that uses the newest multiview-reconstruction 3.2.2 since it contains most of the code required in this spark-project ... I pushed everything upstream, also optimizing it at the same time

**Comment by kgabor** [comment]
@StephanPreibisch Thanks for merging these changes. I'm closing this PR then. When do you plan to merge `overhaul-mvr-322` into `main` ? 

I wanted to try upgrading Spark to 3.3.2 (this is the version run by Amazon EMR serverless).

**Comment by kgabor** [comment]
Superseded by #17.

**Pull request closed without merging**
